### ISSUE TITLE
feature: encoding empty array

### ISSUE THREAD

**Issue by bjne** [bungle/lua-resty-libcjson#1]
Would be nice to be able to set a flag to force a empty table to be
encoded as an array []

Also mentioned here: https://github.com/mpx/lua-cjson/issues/11
and here: http://openmymind.net/Lua-JSON-turns-empty-arrays-into-empty-hashes/

**Comment by apristen** [comment]
thanks!
in which version it is fixed? 
I have lua-cjson-2.1.0.4 and cjson.encode(cjson.decode("[[],{}]")) returns me [{},{}]
