### ISSUE TITLE
Please remove links to sourceforge and kbranigans repo from the readme

### ISSUE THREAD

**Issue by FSMaxB** [bungle/lua-resty-libcjson#10]
The version on sourceforge is outdated and contains several security flaws. Kbranigans fork is currently up to date, but only because I made a pull request that brings it up to date (so that people are not downloading old versions with security flaws from his repo).

So please remove those two links from the readme.

**Comment by bungle** [comment]
ok i will.

**Comment by bungle** [comment]
removed
