### ISSUE TITLE
libcjson.lua:91: cannot resolve symbol 'cJSON_Parse'

### ISSUE THREAD

**Issue by shushan-tong** [bungle/lua-resty-libcjson#14]
```lua
local json = require "resty.libcjson"
local j = json.decode([[
{
	"members": [{
			"id": 1,
			"name": "Peter"
		},
		{
			"id": 2,
			"name": "John"
		},
		{
			"id": 3,
			"name": "Lucy"
		}
	]
}
]])

print(j.members[1].id)

for _, member in ipairs(j.members) do
  print(member.id)
  print(member.name)
end
```

I download the the library [libcjson.lua](https://github.com/bungle/lua-resty-libcjson/blob/master/lib/resty/libcjson.lua) and put it in nginx/resty,when execute your code,I got the error below:

`2018/04/19 21:36:56 [error] 79984#82660: *46877144 lua entry thread aborted: runtime error: ..._Windows_1.13.5.1001_64Bit\x64\nginx//resty\libcjson.lua:91: cannot resolve symbol 'cJSON_Parse'`

**Comment by bungle** [comment]
How have you done this:
https://github.com/bungle/lua-resty-libcjson#compiling-and-installing-cjson-c-library

The resulting shared library needs to be in system library path for FFI wrapper to find it.

**Comment by shushan-tong** [comment]
I find the way to print the element in json array:
local element1=data["members"][1];
ngx.say(cjson.encode(element1));
