### ISSUE TITLE
libcjson.so

### ISSUE THREAD

**Issue by abdulrahmanmadeni** [bungle/lua-resty-libcjson#5]
Hi
I got this message "libcjson.so: cannot open share object file: No such file or directory" even though I follow the instruction given exactly... please advice

**Comment by bungle** [comment]
What operating system are you using, and where have you placed the so/dylib/dll file? Have you tried to point that ffi_load line directly to the shared library file using absolute path?

**Comment by abdulrahmanmadeni** [comment]
This issue already solved by following the instruction given. Thanks. But i
have another one problem comes....

"attemp to index local 'data' (a nil value)"
at wiola.lua file line 278....

please advice me on this...

**Comment by bungle** [comment]
Well, I have no idea what wiola.lua is, and what's on that line 278. It seems you are using `nil` variable (maybe a result of json decoding or something else)?

E.g.

```lua
local a
a.attempt_to_index_nil_value
```

**Comment by bungle** [comment]
The error is on this line, right?
https://github.com/abdulrahmanmadeni/wiola/blob/dev/src/wiola/wiola.lua#L278

What do you pass as data variable to there? It seems like decoding results a nil, so I suspect that you are passing a `nil` value there, or a `empty string`. Those will result `nil` when calling `json.decode`.

**Comment by abdulrahmanmadeni** [comment]
I already checked the content of data and it is not nil value. But I am suspecting 
local json = require "resty.libcjson" 
was compiled wrongly earlier using cJSON.c code.

Where can I get libcjson binary?

**Comment by bungle** [comment]
You can download it from here:
http://sourceforge.net/projects/cjson/'

And compile, you can compile with `-O3` if you like to have some optimizations there.

**Comment by abdulrahmanmadeni** [comment]
I am following instruction given in
https://github.com/bungle/lua-resty-libcjson
to compile the code and produce libcjson.so. But, when I start using json.encode and json.decode, the functions are not exist and found that the C++ code download from your suggested link has not had such function.... please advice me here.

**Comment by bungle** [comment]
You make this really hard. Please provide your input data and the code you are using, e.g.

```lua
local data = "[ 12, 14, 35, 56]"
local json = require "resty.libcjson"
local d = json.decode(data)
print(d[1])
```

The above example should print 12. Are you using LuaJIT or plain PuC-Lua? This doesn't work with PuC Lua as it only has LuaJIT FFI bindings.

**Comment by abdulrahmanmadeni** [comment]
Hi

Sorry to disturb u again. It was fixed, and thanx for your response. To
avoid nil value, I have to use wampy.js pluggin and it fires data to wiola
router.
