### ISSUE TITLE
Memory leak for json encode

### ISSUE THREAD

**Issue by jonas0616** [bungle/lua-resty-libcjson#6]
```lua
#!/usr/bin/env luajit
local json = require "resty.libcjson"
local tbl  = {hello = "world"}

for _ = 1, 100000000 do
    local json_str = json.encode(tbl)
end
```

Run the above code and observe. The memory usage keeps growing during repeated json encode.
However, json decode works just fine.

The version of luajit and lua-resty-libcjson is:
>$ luajit -v
>LuaJIT 2.0.2 -- Copyright (C) 2005-2013 Mike Pall. http://luajit.org/
>$ luarocks list lua-resty-libcjson
>
>Installed rocks:
>
>lua-resty-libcjson
>   1.1-1 (installed) - /usr/local/lib/luarocks/rocks

And cJSON is download from http://sourceforge.net/projects/cjson/files/latest/download
This issue also can be reproduced by openresty 1.7.10.2.

**Comment by bungle** [comment]
Yes, the encode is like total mess with this. On this more up-to-date version there is:
https://github.com/kbranigan/cJSON/commit/dbd0a7098164a2cc118a9f4ef64656f380007ad9

**Comment by bungle** [comment]
Hi, I added small patch, can you check if it helps, also try out kbranigan/cJSON.

**Comment by bungle** [comment]
I already checked, and it doesn't help.

**Comment by ngo** [comment]
This leak is actually pretty bad. In my experience under moderate load (<100 rps), when doing one encode per request this can easily leak 100-150 megs per worker per day. 

I had to switch to pure-lua lunajson lib, which doesn't leak.

**Comment by bungle** [comment]
Yeah, I think the leak is in C-module, and there is little I can do. On OpenResty the bundled Lua cJSON is the preferred lib.

**Comment by bungle** [comment]
If I change code to this:

```lua
function json.encode(value, formatted)
    local j = ffi_gc(json.encval(value), cjson.cJSON_Delete)
    if j == nil then return nil end
    print(collectgarbage("count")*1024)
    collectgarbage()
    collectgarbage()
    return formatted ~= false and ffi_str(cjson.cJSON_Print(j)) or ffi_str(cjson.cJSON_PrintUnformatted(j))
end
```

I get 46465 printed constantly, but the memory grows. So this might be actually a memory leak in LuaJIT.

**Comment by someburner** [comment]
Ah, looks like the reply by corsix may be the issue. For instance in my C code I have to do:
```
	char * json_string;
	json_string = cJSON_Print(root);

	int ret = http_write(c,json_string);
	os_free(json_string);
```

where root is also a malloc'd cJSON object.

**Comment by bungle** [comment]
@someburner I just committed this as 1.2 and after some cleanups 1.3 that fixes this issue. Thanks a lot.

@ngo, @jonas0616, will you also check if it is fixed now, if not, please reopen this issue. Thanks for reporting.

**Comment by ngo** [comment]
@bungle Great work, thanks! My short test (~30 min) shows that the memory leak is gone. I will update once I collect more info overnight.

**Comment by ngo** [comment]
The long test also doesn't show any signs of leaks

**Comment by bungle** [comment]
Thanks @ngo for checking and confirming that the fix had the desired effect.
